# Generated by Django 5.2.16 on 2026-08-30 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsproduct',
            name='interest_term_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='How often interest is credited to the account, in months.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
