# Generated by Django 5.2.16 on 2026-08-30 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsproduct_interest_term_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['account', 'transaction_type', '-created_at'], name='savings_sav_account_958127_idx'),
        ),
    ]
