from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

urlpatterns = [
    path("", views.dashboard, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html", authentication_form=LoginForm), name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("estimate/", views.estimate, name="estimate"),
    path("apply/", views.application_create, name="loan_application"),
    path("applications/<int:pk>/", views.application_detail, name="application-detail"),
    path("applications/<int:pk>/submit/", views.application_submit, name="application-submit"),
    path("loans/", views.my_loan, name="my_loan"),
    path("loans/<int:loan_id>/", views.loan_detail, name="loan_detail"),
    path("loans/<int:loan_id>/schedule/", views.schedule, name="repayment_schedule"),
    path("schedule/", views.my_schedule, name="my_schedule"),
    path("loans/<int:loan_id>/pay/", views.make_payment, name="make_payment"),
    path("documents/", views.simple_page, {"title": "Documents", "description": "Your submitted documents are held securely with your application."}, name="documents"),
    path("notifications/", views.simple_page, {"title": "Notifications", "description": "You are all caught up."}, name="notifications"),
    path("profile/", views.profile, name="profile"),
    path("support/", views.simple_page, {"title": "Support", "description": "Our lending team is here to help explain every part of your application."}, name="support"),
    path("terms/", views.simple_page, {"title": "Terms", "description": "Please review the terms provided with your application."}, name="terms"),
    path("privacy/", views.simple_page, {"title": "Privacy notice", "description": "Your information is used only to review and service your account."}, name="privacy"),
    path("password-reset/", views.simple_page, {"title": "Password reset", "description": "Contact support to reset your demo password."}, name="password_reset"),
    path("borrower/", views.borrower_dashboard, name="borrower_dashboard"),
    path("officer/", views.officer_dashboard, name="officer_dashboard"),
    path("officer/applications/", views.applications, name="applications_queue"),
    path("officer/applications/new/", views.officer_apply_loan, name="officer_apply_loan"),
    path("officer/applications/available-products/", views.officer_available_products, name="officer_available_products"),
    path("officer/products/", views.loan_products, name="loan_products"),
    path("officer/products/add/", views.add_loan_product, name="add_loan_product"),
    path("officer/products/new/", views.add_loan_product_page, name="add_loan_product_page"),
    path("officer/products/<int:product_id>/edit/", views.edit_loan_product, name="edit_loan_product"),
    path("officer/applications/<int:application_id>/review/", views.application_review, name="application_review"),
    path("officer/borrowers/", views.borrowers, name="borrowers"),
    path("officer/members/", views.all_members, name="all_members"),
    path("officer/borrowers/add/", views.add_member, name="add_member"),
    path("officer/loan-officers/", views.loan_officers, name="loan_officers"),
    path("officer/loan-officers/add/", views.add_officer, name="add_officer"),
    path("officer/loan-officers/<int:officer_id>/edit/", views.edit_officer, name="edit_officer"),
    path("officer/loan-officers/<int:officer_id>/activity/", views.officer_activity_log, name="officer_activity_log"),
    path("officer/borrowers/<int:borrower_id>/", views.borrower_detail, name="borrower_detail"),
    path("officer/borrowers/<int:borrower_id>/edit/", views.edit_member, name="edit_member"),
    path("officer/loans/<int:loan_id>/", views.officer_loan_detail, name="officer_loan_detail"),
    path("officer/loans/<int:loan_id>/schedule/", views.officer_schedule, name="officer_repayment_schedule"),
    path("officer/loans/<int:loan_id>/pay/", views.officer_make_payment, name="officer_make_payment"),
    path("officer/disbursement/", views.disbursement, name="disbursements"),
    path("officer/disbursement/<int:disbursement_id>/", views.disburse, name="disbursement_detail"),
    path("officer/disbursement/<int:disbursement_id>/receipt/", views.disbursement_receipt, name="disbursement_receipt"),
    path("officer/reports/", views.reports, name="reports"),
    path("officer/reports/export/", views.export_portfolio_csv, name="export_portfolio_csv"),
    path("officer/applications/export/", views.export_applications_csv, name="export_applications_csv"),
    path("officer/borrowers/export/", views.export_borrowers_csv, name="export_borrowers_csv"),
    path("officer/disbursement/export/", views.export_disbursements_csv, name="export_disbursements_csv"),
    path("loans/<int:loan_id>/schedule.csv", views.schedule_export, name="export_schedule_csv"),
    path("payments/<int:payment_id>/receipt/", views.payment_receipt, name="payment_receipt"),
    path("officer/applications/<int:application_id>/delete/", views.application_delete, name="application_delete"),
    path("officer/applications/<int:application_id>/decision/", views.application_decision, name="application_decision"),
    path("officer/applications/<int:application_id>/note/", views.add_review_note, name="add_review_note"),
]