# Generated by Django 5.2.16 on 2026-08-30 09:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualAidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, help_text='Fixed contribution amount per period.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('contribution_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('max_benefit_amount', models.DecimalField(decimal_places=2, help_text='Maximum benefit payout per approved claim.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('waiting_period_days', models.PositiveSmallIntegerField(default=90, help_text='Days after enrollment before a member can file a claim.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(730)])),
                ('min_membership_months', models.PositiveSmallIntegerField(default=0, help_text='Minimum months of active membership before eligibility.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MutualAidMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('total_contributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('benefits_claimed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_aid_memberships_opened', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutual_aid_memberships', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='mutual_aid.mutualaidplan')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='MutualAidContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('check', 'Check'), ('online', 'Online'), ('payroll_deduction', 'Payroll deduction')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('period_label', models.CharField(blank=True, help_text="Contribution period, e.g. 'Jan 2026' or 'Q1 2026'.", max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_aid_contributions_recorded', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='mutual_aid.mutualaidmembership')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['membership', '-created_at'], name='mutual_aid__members_d70dce_idx')],
            },
        ),
        migrations.CreateModel(
            name='MutualAidClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('death', 'Death of member or dependent'), ('illness', 'Serious illness'), ('hospitalization', 'Hospitalization'), ('emergency', 'Emergency hardship'), ('other', 'Other')], max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(help_text='Describe the circumstance requiring mutual aid.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_aid_claims_disbursed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_aid_claims_reviewed', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='mutual_aid.mutualaidmembership')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='mutual_aid__status_596a20_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mutualaidmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('member', 'plan'), name='unique_active_mutual_aid_membership'),
        ),
    ]
