# Generated by Django 5.2.16 on 2026-08-30 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_aid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mutualaidmembership',
            name='unique_active_mutual_aid_membership',
        ),
        migrations.AddIndex(
            model_name='mutualaidmembership',
            index=models.Index(fields=['member', 'plan', 'status'], name='mutual_aid__member__aedea0_idx'),
        ),
    ]
