# Generated by Django 5.2.16 on 2026-08-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_aid', '0002_remove_mutualaidmembership_unique_active_mutual_aid_membership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualaidcontribution',
            name='period_label',
        ),
        migrations.CreateModel(
            name='MutualAidPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('label', models.CharField(blank=True, help_text="Optional short label, e.g. 'Jan 2026'.", max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='mutual_aid.mutualaidplan')),
            ],
            options={
                'ordering': ['-date_from'],
            },
        ),
        migrations.AddField(
            model_name='mutualaidcontribution',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='mutual_aid.mutualaidperiod'),
        ),
        migrations.AddIndex(
            model_name='mutualaidperiod',
            index=models.Index(fields=['plan', '-date_from'], name='mutual_aid__plan_id_d9050c_idx'),
        ),
    ]
