# Generated by Django 5.2.16 on 2026-09-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_aid', '0004_ensure_kap_mutual_aid_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutualaidcontribution',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
