# Generated by Django 5.2.16 on 2026-08-29 09:36

import lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(lending.models.RoleDefaultMixin, 'lending.user'),
            managers=[
                ('objects', lending.models.RoleScopedManager('admin')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
            ],
            options={
                'verbose_name': 'Loan Officer',
                'verbose_name_plural': 'Loan Officers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(lending.models.RoleDefaultMixin, 'lending.user'),
            managers=[
                ('objects', lending.models.RoleScopedManager('officer')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(lending.models.RoleDefaultMixin, 'lending.user'),
            managers=[
                ('objects', lending.models.RoleScopedManager('member')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Loan Officer'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
