# Generated by Django 5.2.16 on 2026-08-29 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_borrower_role_to_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='other_fees_description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
