# Generated by Django 5.2.16 on 2026-08-30 03:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_loan_other_fees_loan_other_fees_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.DecimalField(decimal_places=3, default=Decimal('100.000'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
