# Generated by Django 5.2.16 on 2026-08-30 03:17

from django.db import migrations, models


def backfill_applied_on(apps, schema_editor):
    LoanApplication = apps.get_model("lending", "LoanApplication")
    for application in LoanApplication.objects.filter(applied_on__isnull=True).iterator():
        application.applied_on = application.created_at.date()
        application.save(update_fields=["applied_on"])


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_user_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='applied_on',
            field=models.DateField(blank=True, help_text='Date the borrower applied for this loan.', null=True),
        ),
        migrations.RunPython(backfill_applied_on, migrations.RunPython.noop),
    ]
