# Generated by Django 5.2.16 on 2026-08-30 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_loan_disbursed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='lending.loanproduct'),
        ),
    ]
