# Generated by Django 5.2.16 on 2026-08-30 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0009_loanproduct_set_null_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='lending.loanapplication'),
        ),
    ]
