# Generated by Django 5.2.16 on 2026-08-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_loan_cascade_on_application_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
            ],
            options={
                'verbose_name': 'Disbursement',
                'verbose_name_plural': 'Disbursements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lending.loan',),
        ),
    ]
