# Generated by Django 5.2.16 on 2026-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0011_disbursement_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Harborline', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Lending workspace', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Features',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
