# Generated by Django 5.2.16 on 2026-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0013_normalize_credit_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after disbursement before interest starts accruing.'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after disbursement before interest starts accruing.'),
        ),
    ]
