# Generated by Django 5.2.16 on 2026-09-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0014_loanproduct_grace_period_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan application', 'verbose_name_plural': 'Loan applications'},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='additional_business_1_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business 1 address'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='additional_business_1_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Business 1 name'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='additional_business_1_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Type of Business 1'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='additional_business_2_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business 2 address'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='additional_business_2_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Business 2 name'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='additional_business_2_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Type of Business 2'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='application_type',
            field=models.CharField(blank=True, choices=[('new', 'New Application'), ('renew', 'Renew Application')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_citizenship',
            field=models.CharField(blank=True, choices=[('filipino', 'Filipino'), ('others', 'Others')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_contact_network',
            field=models.CharField(blank=True, max_length=80, verbose_name='Contact # / Network'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_dwelling_ownership',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('mortgaged', 'Mortgaged'), ('used_free', 'Used Free')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_id_presented',
            field=models.CharField(blank=True, max_length=120, verbose_name='I.D. Presented'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_middle_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_municipality_city',
            field=models.CharField(blank=True, max_length=160, verbose_name='Municipality, Province / City'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_nationality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_period_of_staying',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_permanent_municipality_city',
            field=models.CharField(blank=True, max_length=160, verbose_name='Permanent Municipality, Province / City'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_photo',
            field=models.ImageField(blank=True, null=True, upload_to='loan-applications/photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_place_of_birth',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_present_address',
            field=models.CharField(blank=True, help_text='House #, Street, Subd., Brgy.', max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_signed_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Borrower printed name'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_signed_place',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_spouse_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Name of Spouse (if married)'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_surname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_tel_mobile',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tel or Mobile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_tin_sss',
            field=models.CharField(blank=True, max_length=60, verbose_name='TIN or SSS #'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch_manager_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch_manager_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_ownership',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('mortgaged', 'Mortgaged'), ('used_free', 'Used Free')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_citizenship',
            field=models.CharField(blank=True, choices=[('filipino', 'Filipino'), ('others', 'Others')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_contact_network',
            field=models.CharField(blank=True, max_length=80, verbose_name='Contact # / Network'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_dwelling_ownership',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('mortgaged', 'Mortgaged'), ('used_free', 'Used Free')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_id_presented',
            field=models.CharField(blank=True, max_length=120, verbose_name='I.D. Presented'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_middle_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_municipality_city',
            field=models.CharField(blank=True, max_length=160, verbose_name='Municipality, Province / City'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_nationality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_period_of_staying',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_permanent_municipality_city',
            field=models.CharField(blank=True, max_length=160, verbose_name='Permanent Municipality, Province / City'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_photo',
            field=models.ImageField(blank=True, null=True, upload_to='loan-applications/photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_place_of_birth',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_present_address',
            field=models.CharField(blank=True, help_text='House #, Street, Subd., Brgy.', max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_relationship',
            field=models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('others', 'Others')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_signed_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Co-borrower printed name'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_signed_place',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_spouse_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Name of Spouse (if married)'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_surname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_tel_mobile',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tel or Mobile'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_tin_sss',
            field=models.CharField(blank=True, max_length=60, verbose_name='TIN or SSS #'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='form_ref_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ref No.'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='hold_out_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='insurance_proposed',
            field=models.CharField(blank=True, choices=[('life_3yr', '3 Years Life'), ('pog', 'POG'), ('none', 'No Insurance')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_purpose',
            field=models.CharField(blank=True, choices=[('additional_capital', 'Additional Capital / Business Expansion'), ('existing_improvement', 'Existing Improvement / Repair'), ('others', 'Others')], max_length=40),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='office_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('hold', 'Hold')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='persons_employed',
            field=models.CharField(blank=True, max_length=40, verbose_name='No. of persons employed'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='primary_business',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='recommended_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='recommended_by_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='recommended_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='recommended_loan_period',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reg_barangay',
            field=models.BooleanField(default=False, verbose_name='Barangay Clearance / Permit'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reg_bir',
            field=models.BooleanField(default=False, verbose_name='BIR'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reg_dti',
            field=models.BooleanField(default=False, verbose_name='DTI'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reg_mayor',
            field=models.BooleanField(default=False, verbose_name="Mayor's Permit"),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reg_others',
            field=models.BooleanField(default=False, verbose_name='Other registration'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reg_others_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='Other registration details'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='validated_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='validated_by_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='years_in_operation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='payment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(blank=True, help_text='Details when loan purpose is Others, or free-text notes.'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Flat monthly percentage charged on principal for each month of the term.', max_digits=5),
        ),
        migrations.CreateModel(
            name='CharacterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('contact_number', models.CharField(blank=True, max_length=40, verbose_name='Contact #')),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_references', to='lending.loanapplication')),
            ],
            options={
                'verbose_name': 'Character reference',
                'verbose_name_plural': 'Character references',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
