# Generated by Django 5.2.16 on 2026-09-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0015_kap_loan_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='borrower_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the borrower.', null=True, upload_to='loan-applications/signatures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='coborrower_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the co-borrower.', null=True, upload_to='loan-applications/signatures/%Y/%m/'),
        ),
    ]
