# Generated by Django 5.2.16 on 2026-09-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0017_loan_other_fees_description_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='min_term_months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
