# Generated by Django 5.2.16 on 2026-09-05 07:23

import lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0018_loanproduct_min_term_default_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(lending.models.RoleDefaultMixin, 'lending.user'),
            managers=[
                ('objects', lending.models.RoleScopedManager('manager')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Loan Officer'), ('manager', 'Manager'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
