# Generated by Django 5.2.16 on 2026-09-07 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0024_features_kap_branding_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='savings_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Cash-rounding surplus (adjusted − exact) credited to the member's savings.", max_digits=12),
        ),
    ]
