# Generated by Django 5.2.16 on 2026-09-07 12:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0025_payment_savings_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='daily_mutual_aid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Compulsory mutual aid collected with every working-day remittance (₱). Weekly = ×5, biweekly = ×10, monthly = ×22.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payment',
            name='mutual_aid_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of this remittance credited to KAP mutual aid (₱15 × working days).', max_digits=12),
        ),
    ]
