# Generated by Django 5.2.16 on 2026-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0026_payment_mutual_aid_and_features_daily_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=4, help_text='Calendar day of the week when loan fund releases are allowed.')),
                ('condition_enabled', models.BooleanField(default=True, help_text='When enabled, officers can only disburse on the selected weekday. When disabled, disbursement is allowed any day.')),
            ],
            options={
                'verbose_name': 'Disbursement setting',
                'verbose_name_plural': 'Disbursement settings',
            },
        ),
    ]
