# Generated by Django 5.2.16 on 2026-09-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0027_disbursement_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, help_text='Optional middle initial, e.g. M or M.', max_length=10),
        ),
    ]
