# Generated by Django 5.2.16 on 2026-09-10 11:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0028_user_middle_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementsetting',
            name='disbursement_start_time',
            field=models.TimeField(
                default=datetime.time(8, 0),
                help_text='Local time when officers may start releasing funds on the selected weekday.',
            ),
        ),
        migrations.AlterField(
            model_name='disbursementsetting',
            name='condition_enabled',
            field=models.BooleanField(
                default=True,
                help_text='When enabled, officers can only disburse on the selected weekday after the start time. When disabled, disbursement is allowed any day.',
            ),
        ),
    ]
