# Generated by Django 5.2.16 on 2026-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0029_disbursement_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(
                blank=True,
                help_text='Optional middle name.',
                max_length=80,
                verbose_name='middle name',
            ),
        ),
    ]
