# Generated by Django 5.2.16 on 2026-09-11 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0032_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed login')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Login / logout log',
                'verbose_name_plural': 'Login / logout logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='lending_act_actor_i_945fb3_idx',
            old_name='lending_act_actor_i_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='lending_act_actor_i_4a8f4a_idx',
            old_name='lending_act_actor_k_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('member_created', 'Member created'), ('member_updated', 'Member updated'), ('application_created', 'Application created'), ('application_updated', 'Application updated'), ('application_approved', 'Application approved'), ('application_rejected', 'Application rejected'), ('application_info_requested', 'More information requested'), ('application_deleted', 'Application deleted'), ('review_note', 'Review note added'), ('payment_recorded', 'Pay collection'), ('loan_disbursed', 'Loan disbursed'), ('balance_extended', 'Balance extended'), ('officer_created', 'Officer created'), ('officer_updated', 'Officer updated'), ('manager_created', 'Manager created'), ('manager_updated', 'Manager updated'), ('product_created', 'Product created'), ('product_updated', 'Product updated'), ('savings_opened', 'Savings account opened'), ('savings_deposit', 'Savings deposit'), ('savings_withdrawal', 'Savings withdrawal'), ('savings_closed', 'Savings account closed'), ('mutual_aid_enrolled', 'Mutual aid enrolled'), ('mutual_aid_contribution', 'Mutual aid contribution'), ('mutual_aid_claim', 'Mutual aid claim submitted'), ('mutual_aid_claim_reviewed', 'Mutual aid claim reviewed'), ('mutual_aid_claim_disbursed', 'Mutual aid claim disbursed'), ('membership_status', 'Membership status changed'), ('profile_updated', 'Profile updated'), ('data_exported', 'Data exported'), ('data_imported', 'Data imported'), ('signed_in', 'Signed in'), ('signed_out', 'Signed out'), ('sign_in_failed', 'Failed sign-in')], max_length=40),
        ),
        migrations.AddField(
            model_name='loginlogoutlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logout_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginlogoutlog',
            index=models.Index(fields=['user', 'created_at'], name='lending_log_user_id_ff74d4_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlogoutlog',
            index=models.Index(fields=['user', 'event', 'created_at'], name='lending_log_user_id_0ac635_idx'),
        ),
    ]
