# Generated by Django 5.2.16 on 2026-09-12 05:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0033_loginlogoutlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('member_created', 'Member created'), ('member_updated', 'Member updated'), ('application_created', 'Application created'), ('application_updated', 'Application updated'), ('application_approved', 'Application approved'), ('application_rejected', 'Application rejected'), ('application_info_requested', 'More information requested'), ('application_deleted', 'Application deleted'), ('review_note', 'Review note added'), ('payment_recorded', 'Pay collection'), ('loan_disbursed', 'Loan disbursed'), ('balance_extended', 'Balance extended'), ('expired_month_signed', 'Expired month signed'), ('officer_created', 'Officer created'), ('officer_updated', 'Officer updated'), ('manager_created', 'Manager created'), ('manager_updated', 'Manager updated'), ('product_created', 'Product created'), ('product_updated', 'Product updated'), ('savings_opened', 'Savings account opened'), ('savings_deposit', 'Savings deposit'), ('savings_withdrawal', 'Savings withdrawal'), ('savings_closed', 'Savings account closed'), ('mutual_aid_enrolled', 'Mutual aid enrolled'), ('mutual_aid_contribution', 'Mutual aid contribution'), ('mutual_aid_claim', 'Mutual aid claim submitted'), ('mutual_aid_claim_reviewed', 'Mutual aid claim reviewed'), ('mutual_aid_claim_disbursed', 'Mutual aid claim disbursed'), ('membership_status', 'Membership status changed'), ('profile_updated', 'Profile updated'), ('data_exported', 'Data exported'), ('data_imported', 'Data imported'), ('signed_in', 'Signed in'), ('signed_out', 'Signed out'), ('sign_in_failed', 'Failed sign-in')], max_length=40),
        ),
        migrations.CreateModel(
            name='ExpiredMonthSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('signed_name', models.CharField(blank=True, max_length=160)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature', models.ImageField(upload_to='loan-expired-months/signatures/%Y/%m/')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_month_signatures', to='lending.loan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expired_month_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month_number', 'start_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'month_number', 'start_date'), name='unique_expired_month_signature')],
            },
        ),
    ]
