# Generated by Django 5.2.16 on 2026-09-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0034_alter_activitylog_action_expiredmonthsignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="outstanding_after",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Loan outstanding balance immediately after this payment was applied.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="outstanding_before",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Loan outstanding balance immediately before this payment was applied.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
