# Generated by Django 5.2.16 on 2026-09-15 06:02

from django.db import migrations, models


PURPOSE_MAP = {
    "additional_capital": "business",
    "existing_improvement": "general",
    "others": "general",
}


def remap_loan_purposes(apps, schema_editor):
    LoanApplication = apps.get_model("lending", "LoanApplication")
    for old, new in PURPOSE_MAP.items():
        LoanApplication.objects.filter(loan_purpose=old).update(loan_purpose=new)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0036_backfill_payment_outstanding_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="borrower_monthly_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monthly income",
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="coborrower_monthly_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monthly income",
            ),
        ),
        migrations.RunPython(remap_loan_purposes, noop_reverse),
        migrations.AlterField(
            model_name="loanapplication",
            name="application_type",
            field=models.CharField(
                blank=True,
                choices=[("new", "New Application"), ("renew", "Re-New Application")],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="loan_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General Loan"),
                    ("business", "Business Loan"),
                    ("agricultural", "Agricultural Loan"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
                max_length=20,
            ),
        ),
    ]
