# Generated by Django 5.2.16 on 2026-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0037_kap_application_form_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="schedule_start_date",
            field=models.DateField(
                blank=True,
                help_text="When set, the repayment schedule starts from this date instead of disbursed_date. For balance extensions, must be after the expired maturity date (not that day).",
                null=True,
            ),
        ),
    ]
