# Generated by Django 5.2.16 on 2026-09-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0038_alter_loan_schedule_start_date"),
        ("lending", "0038_rescheduledloan_proxy"),
    ]

    operations = []
