# Generated by Django 5.2.16 on 2026-09-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0039_member_deleted_activity_action"),
        ("lending", "0039_merge_20260918_1039"),
    ]

    operations = []
