# Generated by Django 5.2.16 on 2026-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0040_merge_20260919_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("member_created", "Member created"),
                    ("member_updated", "Member updated"),
                    ("member_deleted", "Member deleted"),
                    ("application_created", "Application created"),
                    ("application_updated", "Application updated"),
                    ("application_approved", "Application approved"),
                    ("application_rejected", "Application rejected"),
                    ("application_info_requested", "More information requested"),
                    ("application_deleted", "Application deleted"),
                    ("review_note", "Review note added"),
                    ("payment_recorded", "Pay collection"),
                    ("loan_disbursed", "Loan disbursed"),
                    ("balance_extended", "Balance extended"),
                    ("expired_month_signed", "Expired month signed"),
                    ("officer_created", "Officer created"),
                    ("officer_updated", "Officer updated"),
                    ("manager_created", "Manager created"),
                    ("manager_updated", "Manager updated"),
                    ("product_created", "Product created"),
                    ("product_updated", "Product updated"),
                    ("savings_opened", "Savings account opened"),
                    ("savings_deposit", "Savings deposit"),
                    ("savings_withdrawal", "Savings withdrawal"),
                    ("savings_transaction_deleted", "Savings transaction deleted"),
                    ("savings_transaction_updated", "Savings transaction updated"),
                    ("savings_account_updated", "Savings account updated"),
                    ("savings_account_deleted", "Savings account deleted"),
                    ("savings_closed", "Savings account closed"),
                    ("mutual_aid_enrolled", "Mutual aid enrolled"),
                    ("mutual_aid_membership_updated", "Mutual aid membership updated"),
                    ("mutual_aid_membership_deleted", "Mutual aid membership deleted"),
                    ("mutual_aid_contribution", "Mutual aid contribution"),
                    ("mutual_aid_contribution_updated", "Mutual aid contribution updated"),
                    ("mutual_aid_contribution_deleted", "Mutual aid contribution deleted"),
                    ("mutual_aid_claim", "Mutual aid claim submitted"),
                    ("mutual_aid_claim_reviewed", "Mutual aid claim reviewed"),
                    ("mutual_aid_claim_disbursed", "Mutual aid claim disbursed"),
                    ("membership_status", "Membership status changed"),
                    ("profile_updated", "Profile updated"),
                    ("data_exported", "Data exported"),
                    ("data_imported", "Data imported"),
                    ("signed_in", "Signed in"),
                    ("signed_out", "Signed out"),
                    ("sign_in_failed", "Failed sign-in"),
                    ("account_locked", "Account locked"),
                ],
                max_length=40,
            ),
        ),
    ]
