# Generated by Django 5.2.16 on 2026-09-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0041_loan_declining_balance_schedule"),
        ("lending", "0043_alter_activitylog_action"),
    ]

    operations = []
